- hosts: all
  become: yes
  roles:
    - geerlingguy.apache

  tasks:
    - name: "UFW - Allow HTTP on port 80"
      ufw:
        rule: allow
        port: "80"
        proto: tcp
    - name: "UFW - Allow HTTP on port 443"
      ufw:
        rule: allow
        port: "443"
        proto: tcp
