- hosts: all
  become: yes
  vars:
    - ansible_python_interpreter: python3
  roles:
    - geerlingguy.apache
    - geerlingguy.apache-php-fpm
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-versions
    - geerlingguy.composer

  tasks:
    - name: "UFW - Allow HTTP on port 80"
      ufw:
        rule: allow
        port: "80"
        proto: tcp
    - name: "UFW - Allow HTTP on port 443"
      ufw:
        rule: allow
        port: "443"
        proto: tcp
